version: "2"

services:
    borgserver:
        container_name: borgserver
        image: valmati/borgserver
        hostname: borgserver
        environment:
            - UID=1001
            - GID=1001
            - TZ=Europe/Madrid
            - RESTRICT_TO_PATH=true
        ports:
            - "2222:22"
        volumes:
            - /media/hd1/appdata/borgserver/host_keys:/etc/ssh/host_keys/
            - /media/hd1/appdata/borgserver/authorized_keys:/etc/authorized_keys/:ro
            - /media/hd1/backups:/backups
        restart: unless-stopped

volumes:
  host_keys:
    driver: local
  authorized_keys:
    driver: local
