version: "2"

services:

  cloudflared:
    container_name: cloudflared
    image: crazymax/cloudflared:latest
    ports:
      - "5053:5053/udp"
      - "49312:49312/tcp"
    environment:
      - TZ='Europe/Madrid'
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.2/dns-query,https://1.0.0.2/dns-query"
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 10.8.1.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "8081:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - PIHOLE_DNS_=10.8.1.2#5053
      - IPv6=false
      - TZ='Europe/Madrid'
      - DNSMASQ_LISTENING=all
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasqd:/etc/dnsmasq.d
    networks:
      net:
        ipv4_address: 10.8.1.100
    dns:
      - 127.0.0.1

volumes:
  etc:
    driver: local
  dnsmasqd:
    driver: local

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.1.0/24
