version: "2.2"

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Madrid
    volumes:
      - config:/config
    ports:
      - 8083:80
      - 443:443
    restart: unless-stopped

volumes:
    config:
        driver: local
