version: "2"

services:

  diun:
    container_name: diun
    image: crazymax/diun:latest
    volumes:      
      - /media/hd1/appdata/diun/data:/data
      - /media/hd1/appdata/diun/config/diun.yml:/diun.yml:ro
      - /media/hd1/appdata/diun/config/custom-images.yml:/custom-images.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Europe/Madrid"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    restart: unless-stopped
