version: "2"

services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1001:1001
    ports:
      - 8096:8096
    volumes:
      - /media/hd1/appdata/jellyfin/config:/config
      - /media/hd1/appdata/jellyfin/cache:/cache
      - /media/hd1/media:/media
      - /media/hd1/media2:/media2:ro
    restart: "unless-stopped"
